"""Tests the new autoregressive generation path (generate_bytes.py):
the trained head producing its own output byte-by-byte, rather than
being scored against real corpus bytes. Checks it runs, stays within
byte range, never touches the graph's frozen edges (read-only, same
contract as everywhere else the head touches the graph), and reports
-- honestly, not just pass/fail -- how it actually behaves: does it
stay coherent, does it degenerate into a repetition loop (the exposure-
bias risk flagged before building this), how does greedy compare to
sampled.
"""
import json
import torch
from collections import Counter

from graph import ESGRGraph
from head_checkpoint import load_head_checkpoint
from head import N_COLUMNS
from generate_bytes import generate_bytes

g = ESGRGraph.load_json("graph.json")
tiles = json.load(open("tiles.json"))
from grammar_extra import load_hub_ids
hub_ids = load_hub_ids()
model, _, _, _ = load_head_checkpoint("head_checkpoint.pt", new_tag_dim=N_COLUMNS)

frozen_idx = g.frozen.nonzero().flatten().tolist()
w_before = g.w[frozen_idx].clone()
tau_before = g.tau[frozen_idx].clone()
n_before = g.n

SEEDS = ["the ", "a ", "science ", "the universe "]

def longest_repeated_tail_cycle(byte_list, min_cycle=2, max_cycle=8):
    """Real check for degenerate looping: does the tail of the sequence
    consist of a short byte pattern repeating >= 4 times in a row?
    Returns the cycle length found, or None."""
    for cyc in range(min_cycle, max_cycle + 1):
        if len(byte_list) < cyc * 4:
            continue
        tail = byte_list[-cyc * 4:]
        chunks = [tuple(tail[i:i + cyc]) for i in range(0, len(tail), cyc)]
        if len(set(chunks)) == 1:
            return cyc
    return None

print("=== greedy (temperature=0, deterministic) ===")
for s in SEEDS:
    text, seq, stopped = generate_bytes(g, model, hub_ids, tiles, s, max_len=120,
                                         temperature=0.0, stop_at_newline=False)
    cyc = longest_repeated_tail_cycle(seq)
    print(f"seed={s!r} stopped_early={stopped} degenerate_cycle={cyc}")
    print(f"  -> {text!r}")

print("\n=== sampled (temperature=0.7) ===")
for s in SEEDS:
    text, seq, stopped = generate_bytes(g, model, hub_ids, tiles, s, max_len=120,
                                         temperature=0.7, stop_at_newline=False, seed=0)
    cyc = longest_repeated_tail_cycle(seq)
    print(f"seed={s!r} stopped_early={stopped} degenerate_cycle={cyc}")
    print(f"  -> {text!r}")

print("\n=== sampled, longer run (temperature=0.7, max_len=400) — does it stay stable? ===")
text, seq, stopped = generate_bytes(g, model, hub_ids, tiles, "the ", max_len=400,
                                     temperature=0.7, stop_at_newline=False, seed=1)
cyc = longest_repeated_tail_cycle(seq)
print(f"len={len(seq)} degenerate_cycle_at_end={cyc}")
print(f"  -> {text!r}")

# real word-boundary check: how many recognizable real tiled words appear
words_in_output = set(tiles.keys()) & set(text.split())
print(f"\nreal tiled words recognizable in this output (exact match, whitespace-split): {sorted(words_in_output)}")

# graph must be untouched -- read-only contract
w_after = g.w[frozen_idx]
tau_after = g.tau[frozen_idx]
moved = int(((w_after != w_before) | (tau_after != tau_before)).sum().item())
assert moved == 0, f"generation must never touch frozen edges, but {moved} moved"
assert g.n == n_before, "generation must never change graph node count"
print(f"\n[PASS] frozen edges disturbed: {moved} (must be 0)")
print(f"[PASS] n unchanged: {g.n == n_before}")

# byte range sanity
for s in SEEDS:
    _, seq, _ = generate_bytes(g, model, hub_ids, tiles, s, max_len=50, temperature=0.5, seed=2)
    assert all(0 <= b <= 255 for b in seq), "every generated byte must be a valid byte value"
print("[PASS] all generated bytes in valid range 0-255")

print("\nAll generate_bytes checks ran (see behavior notes above -- this is a real, honest report, not a pass/fail on generation quality).")
